{% extends 'layout.phtml' %}
{% block body %}

    <div class="row">
            <div class="col-lg-12">
                <h1>Employees   List</h1>
                <div class="panel panel-default">
                  <div class="panel-body">
                         <div class="input-group">
                          <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Searh</button>
                          </span>
                          <input type="text" class="form-control" placeholder="user@fanfare.com">
                        </div><!-- /input-group -->
                  </div>
                </div>
            </div>
            <div class="col-lg-12">
                <table class="table">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Email</th>
                      <th>Position</th>
                      <th>Salary</th>
                      <th>Detail</th>
                    </tr>
                  </thead>
                  <tbody>
                    <?php
                     $_path_rel= explode("/", $_SERVER['REQUEST_URI']);

                     $_path_rel_nuw="";
                     for ($i = 0; $i < count($_path_rel) -1; $i++) {
                            if(!is_null($_path_rel[$i]) and !empty($_path_rel[$i]))
                            {
                                $_path_rel_nuw = $_path_rel_nuw. "/".$_path_rel[$i]; 
                            }
                        }

                    foreach ($listEmployees as $empleado)
                    { 
                    ?>
                        <tr>
                            <td><?php echo $empleado['name'] ?></td>
                            <td><?php echo $empleado['email'] ?></td>
                            <td><?php echo $empleado['position'] ?></td>
                            <td><?php echo $empleado['salary'] ?></td>
                            <td>
                                <a href="<?php echo $_path_rel_nuw."/employeDetail/".$empleado['id'];?>">Details</a>
                            </td>
                        </tr>
                        
                    <?php 
                    };
                    ?>
                  </tbody>
                </table>
            </div>
          </div>
      </div>
{% endblock %}
