<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <style>
            .starter-template {
                padding: 40px 15px;
                
            }
        </style>
        
    </head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/devsac/public/"> Developers SAC</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/devsac/public/employees">Employees</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <div class="starter-template">
          <div class="row">
            <div class="col-lg-12">
                <h1> Employe Detail</h1>
                <div class="panel panel-default">
                  <div class="panel-body">
                        <div class="col-sm-6">
                            <div class="form-group">
                              <label class="control-label" for="nameinp">Name</label>
                              
                              <input class="form-control" type="text" id="nameinp" value="<?php echo $employeeReturn['name']; ?>" readonly>
                            </div>
                            <div class="form-group">
                              <label class="control-label" for="emailinp">Email</label>
                              <input class="form-control" type="text" id="emailinp" value="<?php echo $employeeReturn['email']; ?>" readonly>
                            </div>
                            <div class="form-group">
                              <label class="control-label" for="phoneinp">Phone</label>
                              <input class="form-control" type="text" id="phoneinp" value="<?php echo $employeeReturn['phone']; ?>" readonly>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                              <label class="control-label" for="addressinp">Address</label>
                              <input class="form-control" type="text" id="addressinp" value="<?php echo $employeeReturn['address']; ?>" readonly>
                            </div>
                          
                            <div class="form-group">
                              <label class="control-label" for="positioninp">Position</label>
                              <input class="form-control" type="text" id="positioninp" value="<?php echo $employeeReturn['position']; ?>" readonly>
                            </div>
                            <div class="form-group">
                              <label class="control-label" for="salaryinp">Salary</label>
                              <input class="form-control" type="text" id="salaryinp" value="<?php echo $employeeReturn['salary']; ?>" readonly>
                            </div>
                        </div>
                  </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title"><strong>Skills</strong></h3>
                  </div>
                  <div class="panel-body">
                    <div class="table-responsive">
                      <table class="table table-condensed">
                        <thead>
                              <tr>
                                
                                <td><strong>Name</strong></td>
       
                              </tr>
                        </thead>
                        <tbody>
                          <!-- foreach ($order->lineItems as $line) or some such thing here -->
                          <tr>
                            <td>BS-200</td>
                            
                          </tr>
                          <?php
                            foreach ($employeeReturn['skills'] as $skill)
                            {
                                echo '<tr><td>' .$skill['skill'] .'</td><tr>';
                            };
                          ?>
                                        
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
            </div>
          </div>
      </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  

</body>
</html>
